app/urls.py
from django.conf.urls import patterns, url

from app import views

urlpatterns = patterns('',
    # V I E W S
    
    url(r'^$', views.index, name='index'),
    #/app/sprint-list
    url(r'^sprint-list$', views.sprint_list, name='sprint_list'),
    #/app/sprint/3/
    url(r'^sprint/(?P<sprint_id>\d+)/$', views.sprint_detail, name='sprint_detail'),
    #/app/sprint/3/edit
    url(r'^sprint/(?P<sprint_id>\d+)/edit$', views.sprint_edit, name='sprint_edit'),
    #app/sprint/new
    url(r'^sprint/new$', views.sprint_edit, name='sprint_edit'),
    
    #/app/task-list
    url(r'^task-list$', views.task_list, name='task_list'),
    #app/task/3/
    url(r'^task/(?P<task_id>\d+)/$', views.task_edit, name='task_edit'),
    #app/task/new
    url(r'^task/new/$', views.task_edit, name='task_edit'),

    
    # A P I
	
	url(r'^api/save-task/(?P<task_id>\d+)$', views.save_task, name='save_task'),
	url(r'^api/save-task/$', views.save_task, name='save_task'),

	url(r'^api/save-sprint/(?P<sprint_id>\d+)$', views.save_sprint, name='save_sprint'),
	url(r'^api/save-sprint/$', views.save_sprint, name='save_sprint'),

	url(r'^api/delete-task/$', views.delete_task, name='delete_task'),
    url(r'^api/delete-sprint/$', views.delete_sprint, name='delete_sprint'),


)

mySprint/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mySprint.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^app/', include('app.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

app/models.py
from django.db import models

from django.forms import ModelForm

from django.db.models import Sum


class Sprint(models.Model):
	
	NEW = 'NEW'
	STARTED = 'STARTED'
	COMPLETED = 'COMPLETED'

	SPRINT_STATUS_CHOICES = (
        (NEW, 'NEW'),
        (STARTED, 'STARTED'),
        (COMPLETED, 'COMPLETED'),
    )

	sprint_name = models.CharField(max_length=80)
	date_begin = models.DateField('start date')
	date_end = models.DateField('end date')
	duration = models.DecimalField(max_digits=4, decimal_places=1, default=1)
	status = models.CharField(max_length=9, choices=SPRINT_STATUS_CHOICES, default=NEW)

	def __str__(self):
		return self.sprint_name

	def complete_ratio(self):
		task_list = Task.objects.filter(sprint=self.id)
		estimated_sum = task_list.aggregate(Sum('estimated_time')).get('estimated_time__sum')
		elapsed_time = task_list.aggregate(Sum('elapsed_time')).get('elapsed_time__sum')
		return  str(elapsed_time) + ' / ' + str(estimated_sum)

	def complete_ratio_percent(self):
		task_list = Task.objects.filter(sprint=self.id)
		estimated_sum = task_list.aggregate(Sum('estimated_time')).get('estimated_time__sum')
		elapsed_time = task_list.aggregate(Sum('elapsed_time')).get('elapsed_time__sum')
		if elapsed_time and estimated_sum:
			return  elapsed_time / estimated_sum * 100
		else:
			return ""

	def task_total_estimated_time(self):
		task_list = Task.objects.filter(sprint=self.id)
		estimated_sum = task_list.aggregate(Sum('estimated_time')).get('estimated_time__sum')
		return str(estimated_sum)
			

class SprintForm(ModelForm):
	class Meta:
		model = Sprint
		fields = ['sprint_name','date_begin', 'date_end', 'duration', 'status']		


class Task(models.Model):
	sprint = models.ForeignKey(Sprint)
	task_name = models.CharField(max_length=80)
	description = models.TextField(max_length=400)
	estimated_time = models.DecimalField(max_digits=3, decimal_places=1)
	elapsed_time = models.DecimalField(max_digits=3, decimal_places=1, default=0)
	done = models.BooleanField(default=False)

	def __str__(self):
		return self.task_name

class TaskForm(ModelForm):
	class Meta:
		model = Task
		fields = ['sprint','task_name', 'description', 'estimated_time', 'elapsed_time', 'done']

app/views.py
from django.shortcuts import render

from django.http import HttpResponse, HttpResponseRedirect

from app.models import Sprint, Task, TaskForm, SprintForm

# V I E W S

def index(request):
	return render (request, 'app/index.html', {})

def sprint_list(request):
	sprint_list = Sprint.objects.order_by('-id')
	return render (request, 'app/sprint-list.html', {"sprint_list": sprint_list})

def task_list(request):
	task_list = Task.objects.order_by('-id')
	return render (request, 'app/task-list.html', {"task_list": task_list})

def sprint_detail(request, sprint_id):
	sprint = Sprint.objects.get(id=sprint_id)
	return render (request, 'app/sprint-detail.html', {"sprint": sprint})

def sprint_edit(request, sprint_id=None):

	if sprint_id:
		sprint = Sprint.objects.get(id=sprint_id)
		form = SprintForm(instance=sprint)
	else:
		form = SprintForm()

	context =  {
	"form": form,
	"sprint_id": sprint_id
	}

	return render(request, 'app/sprint-edit.html', context)


def task_edit(request, task_id=None):

	modal_flag = (request.POST.get("modalFlag") == "true")
	sprint_id = request.POST.get("sprintID")

	if task_id:
		task = Task.objects.get(id=task_id)
		form = TaskForm(instance=task)
	else:
		form = TaskForm(initial={'sprint': sprint_id})

	context =  {
	"form": form,
	"task_id": task_id
	}

	if modal_flag:
		context["base_template"] = "app/task-edit.html"
		return render(request, 'app/modalWindowBase.html', context)
	else:
		return render(request, 'app/task-edit.html', context)

# A P I

def save_task(request, task_id=None):
	if request.method == 'POST':
		if task_id:
			task = Task.objects.get(id=task_id)
			form = TaskForm(request.POST, instance=task)
		else:
			form = TaskForm(request.POST)
		
		newTask = form.save()

		context =  {
			"form": form,
			"task_id": newTask.id
		}

		return HttpResponseRedirect('/app/task/' + str(newTask.id))

def save_sprint(request, sprint_id=None):
	if request.method == 'POST':
		if sprint_id:
			sprint = Sprint.objects.get(id=sprint_id)
			form = SprintForm(request.POST, instance=sprint)
		else:
			form = SprintForm(request.POST)
		
		newSprint = form.save()

		context =  {
			"form": form,
			"sprint_id": newSprint.id
		}

		return HttpResponseRedirect('/app/sprint/' + str(newSprint.id))

def delete_task(request):
	task_id = request.POST.get("id")
	if task_id != None:
		
		try:
			task = Task.objects.get(id=task_id)
		except Task.DoesNotExist:
			return HttpResponse("Error There is no task with id: " + task_id)
		
		task.delete()
		
		return HttpResponse("Task " + task_id + " successfully deleted!")
	
	else:
		return HttpResponse("Error: task id expected")

def delete_sprint(request):
	sprint_id = request.POST.get("id")
	if sprint_id != None:
		
		try:
			sprint = Sprint.objects.get(id=sprint_id)
		except sprint.DoesNotExist:
			return HttpResponse("Error There is no sprint with id: " + sprint_id)
		
		sprint.delete()
		
		return HttpResponse("sprint " + sprint_id + " successfully deleted!")
	
	else:
		return HttpResponse("Error: sprint id expected")

app/templates/app/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>My Sprint</title>
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		{% load staticfiles %}
		<script type="text/javascript" src="{% static "app/lib/jquery-1.11.3.js" %}"></script>
		<script type="text/javascript" src="{% static "app/lib/bootstrap.min.js" %}"></script>
		<script type="text/javascript" src="{% static "app/js/api.js" %}"></script>
		<link rel=stylesheet href="{% static "app/css/bootstrap.min.css" %}">
		<link rel=stylesheet href="{% static "app/css/bootstrap-theme.min.css" %}">
		
	</head>
	<body>
		<a class="btn btn-default" href="/app/" role="button">Home</a>
		<div class="container">
			{% block content %}
			{% endblock %}
			
			<!-- Modal -->
			<div class="modal fade" id="ModalWindow" role="dialog">
			</div>
		</div>
	</div>
</body>
</html>

app/templates/app/index.html
{% extends "app/base.html" %}
{% block content %}
<p><a href="/app/sprint-list">Sprint list</a></p>
<p><a href="/app/task-list">Task list</a></p>

<p><a href="/app/sprint/new">Add Sprint</a></p>
<p><a href="/app/task/new">Add Task</a></p>
{% endblock %}

app/templates/app/modalWindowBase.html
<div class="modal-dialog">
	<!-- Modal content-->
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h3>Edit task</h3>
		</div>
		<div class="modal-body">
			{% include base_template %}
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		</div>
	</div>
</div>

app/templates/app/sprint-detail.html
{% extends "app/base.html" %}
{% block content %}
    <h1>
    <a class="btn btn-default glyphicon glyphicon-edit" href="/app/sprint/{{sprint.id}}/edit" role="button" title="Edit sprint"></a>
    <button type="button" class="btn btn-danger glyphicon glyphicon-remove-circle" title="Delete sprint" onclick="api.deleteSprint({{sprint.id}})"></button>
    {{ sprint.sprint_name }} | {{ sprint.date_begin}} - {{ sprint.date_end}}
    
    {% if sprint.status == 'STARTED' %}
        <p>
            <div class="row">
                <div class="col-sm-4">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="{{ sprint.complete_ratio_percent}}" aria-valuemin="0" aria-valuemax="{{sprint.duration}}" style="width:{{ sprint.complete_ratio_percent}}%">
                            <span>{{ sprint.complete_ratio}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </p>
    {% endif %}
    </h1>
    
    {% if sprint.status == 'NEW' %}
        <div class="well">
            <div class="bg-info">
                <div class="glyphicon glyphicon-info-sign"></div>
                Hint: Fill your new sprint with tasks up to sprint duration then start your sprint
            </div>

            <p>Task total estimated time (hours) / Sprint duration (hours) : {{ sprint.task_total_estimated_time }} / {{ sprint.duration }}</p>
            <button type="button" class="btn btn-success">Start Sprint</button>
        </div>
    {% endif %}

    <div class="panel panel-default">
        <div class="panel-heading">Tasks:</div>
            <div class="list-group">
                <div class="list-group-item">

                    </div>
                {% for task in sprint.task_set.all %}
                    <div class="list-group-item">
                        <a href="/app/task/{{ task.id }}/">
                            {{ task.task_name }} {{ task.elapsed_time }}/{{ task.estimated_time }} h done: {{task.done}}
                        </a>
                        <button title="Удалить задачу" type="button" class="btn btn-xs btn-danger" onclick="api.deleteTask({{task.id}})">X</button>
                        <button type="button" class="btn btn-xs btn-default glyphicon glyphicon-edit" onclick="api.modalTaskEdit({{task.id}})">Edit</button>
                    </div>
                {% endfor %}
            </div>
    </div>
    
    
{% endblock %}

app/templates/app/sprint-edit.html
{% extends "app/base.html" %}
{% block content %}
{% if sprint_id == None %}
	<form method="post" action="/app/api/save-sprint/">
{% else %}
	<form method="post" action="/app/api/save-sprint/{{sprint_id}}">
{% endif %}
{% csrf_token %}
{% for field in form %}
	{{ field.label_tag }} {{ field }}
	<br>
{% endfor %}
	 <input type="submit" value="Save" />
</form>
{% endblock %}

app/templates/app/sprint-list.html
{% extends "app/base.html" %}
{% block content %}
		<p>sprint-list</p>
		<a href="/app/sprint/new">
			+ Add new sprint
		</a>
		{% if sprint_list %}
			<ul>
				{% for sprint in sprint_list %}
					<li>
						<a href="/app/sprint/{{ sprint.id }}/">
							{{ sprint.sprint_name }} | {{ sprint.date_begin}} - {{ sprint.date_end}} | {{ sprint.complete_ratio}}
						</a>
					</li>
				{% endfor %}
			</ul>
		{% else %}
			<p>No sprints are available.</p>
		{% endif %}
{% endblock %}

app/templates/app/task-edit.html
{% block content %}
{% if task_id == None %}
	<form id="editForm" method="post" action="/app/api/save-task/">
{% else %}
	<form id="editForm" method="post" action="/app/api/save-task/{{task_id}}">
{% endif %}
{% csrf_token %}
{% for field in form %}
	{{ field.label_tag }} {{ field }}
	<br>
{% endfor %}
	 <input type="submit" class="btn btn-primary" value="Save" />
</form>
<SCRIPT TYPE="text/javascript">
$(function(){
	$("#editForm").submit(function(e){
	    e.preventDefault();
	    var $form = $(this);
	    $.post($form.attr("action"), $form.serialize(), function(data) {
	            $("#ModalWindow").modal("hide");
	    	})
	})
});
</SCRIPT>
{% endblock %}

app/templates/app/task-list.html
{% extends "app/base.html" %}
{% block content %}
		<p>task-list</p>
		<a href="/app/task/new">
			+ Add new task
		</a>
		{% if task_list %}
			<ul>
				{% for task in task_list %}
					<li>
						<a href="/app/task/{{ task.id }}/">
							{{ task.task_name }}
						</a>
					</li>
				{% endfor %}
			</ul>
		{% else %}
			<p>No tasks are available.</p>
		{% endif %}
{% endblock %}